spring:
  datasource:
    url: jdbc:mysql://60.205.3.105:3306/zhenhaochi?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
    username: admin
    password: Admin!@4516
    driver-class-name: com.mysql.cj.jdbc.Driver
